### ISSUE TITLE
holiday time ideas,

### ISSUE THREAD

**Issue by MelodyLockstar** [Sinnoma/AntiT-Cogs#5]
New Years - December 31st/ January 1st
groundhog day - February 2nd
valentines day - February 14th
St Patricks day - March 17th
April fools - April 1st
May Day(international workers day) - may 1st
Star wars day - may 4th
Solstice (southern Hemisphere) - June 21st
International talk like a pirate day - September 19th
Halloween - October 31st
day of the dead/all saints day - November 1st
Remembrance day - November 11th
Solstice (Northern Hemisphere) - December 21st
Christmas - December 25th
Boxing day - December 26th

Other holidays without a fixed date 
Lunar new year (late January - early February) 
Ramadan (9th month of islamic calendar) 
Diwali (mid October - mid November)
Easter (the first Sunday after the Paschal full moon/the first full moon after the vernal equinox march - april)
Hanukkah - ( Hanukkah is observed for eight nights and days, starting on the 25th day of Kislev according to the Hebrew calendar, which may occur at any time from late November to late December in the Gregorian calendar)

**Comment by Sinnoma** [comment]
I will keep those one :

- New year
- Valentine day
- St Patrick day
- April fool
- May day
- Solstice
- Christmas (Already done)

**Comment by Sinnoma** [comment]
Everything has been done, but some things hasn't been added finally.
